Repository carlafalk/TodoCalender, pull requests merged in 2022-06, with the labels that each got.

#85 redid logic for display current day
  JS/today.js
Labels: bug

#88 handle different responses from location api
  JS/today.js
Labels: bug

#99 fixed bug with scew div in header
  CSS/Desktop/header.css
  HTML/index.html
Labels: fix

#103 fixed some design issues with editmodal
  CSS/Desktop/sidebar.css
Labels: design, fix

#116 fixed some alignments and buttonsizes etc.
  CSS/Desktop/sidebar.css
  CSS/mobile.css
  CSS/tablet.css
  HTML/index.html
Labels: design

#125 fixed scroll and overfloww issues
  CSS/Desktop/sidebar.css
  CSS/mobile.css
  CSS/tablet.css
Labels: bug

#128 126 display todo description when clicked
  CSS/mobile.css
  CSS/tablet.css
  JS/calendar.js
  JS/todo.js
  JS/variables.js
Labels: enhancement
